spring:
  application:
      name: ${APP_NAME:regular}
  datasource:
    url: ${DATASOURCE_URL:jdbc:mysql://localhost:3306/regular}
    driver-class-name: ${DATASOURCE_DRIVER:com.mysql.cj.jdbc.Driver}
    username:  ${DATASOURCE_USERNAME:root}
    password: ${DATASOURCE_PASSWORD:root}
  jpa:
    hibernate:
      ddl-auto: ${DDL_AUTO:update}
    show-sql: ${SHOW_SQL:true}
